-- 테이블 생성

-- 1. 회원테이블
CREATE TABLE MEMBER (
  MEMBER_ID VARCHAR(255) NOT NULL,
  TEAM_ID   VARCHAR(255),
  USERNAME  VARCHAR(255),
  PRIMARY KEY (MEMBER_ID)
);
-- 2. 팀테이블
CREATE TABLE TEAM (
  TEAM_ID VARCHAR(255) NOT NULL,
  NAME    VARCHAR(255),
  PRIMARY KEY (TEAM_ID)
);
-- 3. 제약조건(참조키 설정)
ALTER TABLE MEMBER
  ADD CONSTRAINT FK_MEMBER_TEAM
FOREIGN KEY (TEAM_ID)
REFERENCES TEAM;

-- 값 입력
-- 1. 팀 입력
INSERT INTO TEAM (TEAM_ID, NAME) VALUES ('Team1', '팀01');
-- 2. 회원 입력
INSERT INTO MEMBER (MEMBER_ID, TEAM_ID, USERNAME) VALUES ('Member1', 'Team1', '회원01');
INSERT INTO MEMBER (MEMBER_ID, TEAM_ID, USERNAME) VALUES ('Member2', 'Team1', '회원02');

-- 값 조회 (팀01에 소속된 회원 조회)
SELECT T.*
FROM MEMBER M
  JOIN TEAM T ON M.TEAM_ID - T.TEAM_ID
WHERE M.MEMBER_ID = 'member1';

-- 단방향 연관관계 확인 JOIN SQL
SELECT
  M.MEMBER_ID,
  M.USERNAME,
  M.TEAM_ID,
  T.NAME AS TEAM_NAME
FROM MEMBER M
  JOIN TEAM T ON M.TEAM_ID = T.TEAM_ID;


