-- 회원 테이블 생성
CREATE TABLE MEMBER
(
  MEMBER_ID VARCHAR(255) NOT NULL,
  TEAM_ID   VARCHAR(255),
  USERNAME  VARCHAR(255),
  PRIMARY KEY (MEMBER_ID)
);

-- 팀 테이블 생성
CREATE TABLE TEAM
(
  TEAM_ID VARCHAR(255) NOT NULL,
  NAME    VARCHAR(255),
  PRIMARY KEY (TEAM_ID)
);

-- 제약 조건 외래키 생성
ALTER TABLE MEMBER
  ADD CONSTRAINT FK_MEMBER_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TEAM;


-- 팀 동록 SQL
INSERT INTO TEAM(TEAM_ID, NAME)
VALUES ('team1', '팀01');

-- 회원 등록 SQL
-- 회원1
INSERT INTO MEMBER(MEMBER_ID, TEAM_ID, USERNAME)
VALUES ('member1', 'team1', '회원01');
-- 회원2
INSERT INTO MEMBER(MEMBER_ID, TEAM_ID, USERNAME)
VALUES ('member2', 'team1', '회원02');

-- 회원01이 소속된 팀 조회
SELECT T.*
FROM MEMBER M
       JOIN TEAM T ON M.TEAM_ID = T.TEAM_ID
WHERE M.TEAM_ID = 'member01';
