@startuml

title 테이블에서 불가능한 N:M 다대다

!define table(x) class x << (T,#FFAAAA) >>
!define primary_key(x) <b>x</b>
!define foreign_key(x) <u>x</u>
hide methods
hide stereotypes

table(MEMBER) {
    primary_key(MEMBER_ID)
    USERNAME
}

table(PRODUCT) {
    primary_key(PRODUCT_ID)
    NAME
}

MEMBER }o--o{ PRODUCT

@enduml
