@startuml

title 필수적 비식별 관계

!define table(x) class x << (T,#FFAAAA) >>
!define primary_key(x) <b>x</b>
!define foreign_key(x) <u>x</u>
hide methods
hide stereotypes

table(PARENT) {
    primary_key(PARENT_ID)
    NAME
}

table(CHILD) {
    primary_key(CHILD_ID)
    foreign_key(PARENT_ID)
    NAME
}

PARENT ||..o{ CHILD

@enduml